//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "pending_sync_transactions")]
pub struct Model {
        pub user_id: i32,
        pub transaction_id: i32,
        #[sea_orm(primary_key)]
        pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
        #[sea_orm(
                belongs_to = "super::transaction_records::Entity",
                from = "Column::TransactionId",
                to = "super::transaction_records::Column::Id",
                on_update = "NoAction",
                on_delete = "NoAction"
        )]
        TransactionRecords,
        #[sea_orm(
                belongs_to = "super::users::Entity",
                from = "Column::UserId",
                to = "super::users::Column::Id",
                on_update = "NoAction",
                on_delete = "NoAction"
        )]
        Users,
}

impl Related<super::transaction_records::Entity> for Entity {
        fn to() -> RelationDef {
                Relation::TransactionRecords.def()
        }
}

impl Related<super::users::Entity> for Entity {
        fn to() -> RelationDef {
                Relation::Users.def()
        }
}

impl ActiveModelBehavior for ActiveModel {}
