//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
        #[sea_orm(primary_key)]
        pub id: i32,
        pub created_at: DateTimeWithTimeZone,
        #[sea_orm(unique)]
        pub session_token: Uuid,
        pub password: String,
        #[sea_orm(unique)]
        pub username: String,
        #[sea_orm(unique)]
        pub email: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
        #[sea_orm(has_many = "super::pending_sync_transactions::Entity")]
        PendingSyncTransactions,
        #[sea_orm(has_many = "super::transaction_records::Entity")]
        TransactionRecords,
}

impl Related<super::pending_sync_transactions::Entity> for Entity {
        fn to() -> RelationDef {
                Relation::PendingSyncTransactions.def()
        }
}

impl Related<super::transaction_records::Entity> for Entity {
        fn to() -> RelationDef {
                Relation::TransactionRecords.def()
        }
}

impl ActiveModelBehavior for ActiveModel {}
