use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
        fn name(&self) -> &str {
                "m20260804_103051_add_session_token"
        }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
        async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
                let db = manager.get_connection();
                db.execute_unprepared("
-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- Due to circular dependencies, the order in which Schema Diff writes objects may not be optimal 
-- and manual changes to the script may be required to ensure changes are applied in the correct order.
-- Please report any issues along with steps to reproduce. 
 BEGIN; 
 ALTER TABLE IF EXISTS public.registration_entries DROP CONSTRAINT IF EXISTS unique_token;

ALTER TABLE IF EXISTS public.registration_entries
    ADD CONSTRAINT unique_key_token UNIQUE (token);
ALTER TABLE IF EXISTS public.users
    ADD COLUMN session_token uuid NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT unique_key_session_token UNIQUE (session_token);

 END;
 ").await?;

                Ok(())
        }

        async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
                let db = manager.get_connection();
                db.execute_unprepared("
-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- Due to circular dependencies, the order in which Schema Diff writes objects may not be optimal 
-- and manual changes to the script may be required to ensure changes are applied in the correct order.
-- Please report any issues along with steps to reproduce. 
 BEGIN; 
 ALTER TABLE IF EXISTS public.registration_entries DROP CONSTRAINT IF EXISTS unique_key_token;

ALTER TABLE IF EXISTS public.registration_entries
    ADD CONSTRAINT unique_token UNIQUE (token);
ALTER TABLE IF EXISTS public.users DROP COLUMN IF EXISTS session_token;

 END;
 ").await?;

                Ok(())
        }
}
