use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
        fn name(&self) -> &str {
                "m20260820_065541_add_primary_key_to_pending_sync_transactions"
        }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
        async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
                let db = manager.get_connection();
                db.execute_unprepared(
                        r#"
ALTER TABLE IF EXISTS public.pending_sync_transactions
    ADD COLUMN id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 );
ALTER TABLE IF EXISTS public.pending_sync_transactions
    ADD CONSTRAINT pending_sync_transactions_pkey PRIMARY KEY (id);"#,
                )
                .await?;

                Ok(())
        }

        async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
                let db = manager.get_connection();
                db.execute_unprepared(
                        r#"
ALTER TABLE IF EXISTS public.pending_sync_transactions DROP COLUMN IF EXISTS id;
ALTER TABLE IF EXISTS public.pending_sync_transactions
    DROP CONSTRAINT pending_sync_transactions_pkey;"#,
                )
                .await?;

                Ok(())
        }
}
