use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
        async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
                let db = manager.get_connection();
                db.execute_unprepared("
-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- Due to circular dependencies, the order in which Schema Diff writes objects may not be optimal 
-- and manual changes to the script may be required to ensure changes are applied in the correct order.
-- Please report any issues along with steps to reproduce. 
 BEGIN; 
 CREATE TABLE IF NOT EXISTS public.seaql_migrations
(
    version character varying COLLATE pg_catalog.\"default\" NOT NULL,
    applied_at bigint NOT NULL,
    CONSTRAINT seaql_migrations_pkey PRIMARY KEY (version)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.seaql_migrations
    OWNER to postgres;
CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog.\"default\" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now() NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;
CREATE TABLE IF NOT EXISTS public.registration_entries
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) STORAGE PLAIN COMPRESSION lz4 COLLATE pg_catalog.\"default\",
    token character varying(5) STORAGE PLAIN COMPRESSION lz4 COLLATE pg_catalog.\"default\" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT registration_entries_pkey PRIMARY KEY (id),
    CONSTRAINT unique_token UNIQUE (token)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.registration_entries
    OWNER to postgres;
CREATE TABLE IF NOT EXISTS public.transaction_records
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(50) STORAGE PLAIN COMPRESSION lz4 COLLATE pg_catalog.\"default\" NOT NULL,
    description character varying(200) STORAGE PLAIN COMPRESSION lz4 COLLATE pg_catalog.\"default\" NOT NULL,
    amount bigint NOT NULL,
    is_income boolean NOT NULL,
    creator_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT transaction_records_pkey PRIMARY KEY (id),
    CONSTRAINT \"fk-transaction_records-creator_id\" FOREIGN KEY (creator_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.transaction_records
    OWNER to postgres;
CREATE SEQUENCE IF NOT EXISTS public.registration_entries_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.registration_entries_id_seq
    OWNER TO postgres;
CREATE SEQUENCE IF NOT EXISTS public.transaction_records_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.transaction_records_id_seq
    OWNER TO postgres;
CREATE SEQUENCE IF NOT EXISTS public.users_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.users_id_seq
    OWNER TO postgres;

 END;
 ").await?;
                Ok(())
        }

        async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
                let db = manager.get_connection();
                db.execute_unprepared("
-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- Due to circular dependencies, the order in which Schema Diff writes objects may not be optimal 
-- and manual changes to the script may be required to ensure changes are applied in the correct order.
-- Please report any issues along with steps to reproduce. 
 BEGIN; 
 DROP TABLE IF EXISTS public.seaql_migrations CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.registration_entries CASCADE;
DROP TABLE IF EXISTS public.transaction_records CASCADE;
DROP SEQUENCE IF EXISTS public.registration_entries_id_seq;
DROP SEQUENCE IF EXISTS public.transaction_records_id_seq;
DROP SEQUENCE IF EXISTS public.users_id_seq;

 END;").await?;

                Ok(())
        }
}
