//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::registration_entries::Entity as RegistrationEntries;
pub use super::transaction_records::Entity as TransactionRecords;
pub use super::users::Entity as Users;
