import type { Metadata } from "next";
import { Saira, Google_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Saira({
        variable: "--font-saira",
        subsets: ["latin"],
});

const geistMono = Google_Sans({
        variable: "--font-google-sans",
        subsets: ["latin"],
});

export const metadata: Metadata = {
        title: "Create Next App",
        description: "Generated by create next app",
};

export default function RootLayout({
        children,
}: Readonly<{
        children: React.ReactNode;
}>) {
        return (
                <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
                        <body className="min-h-full flex flex-col">{children}</body>
                </html>
        );
}
