//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "transaction_records")]
pub struct Model {
        #[sea_orm(primary_key)]
        pub id: i32,
        pub title: String,
        pub description: String,
        pub amount: i64,
        pub is_income: bool,
        pub creator_id: i32,
        pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
        #[sea_orm(
                belongs_to = "super::users::Entity",
                from = "Column::CreatorId",
                to = "super::users::Column::Id",
                on_update = "NoAction",
                on_delete = "NoAction"
        )]
        Users,
}

impl Related<super::users::Entity> for Entity {
        fn to() -> RelationDef {
                Relation::Users.def()
        }
}

impl ActiveModelBehavior for ActiveModel {}
