//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
        #[sea_orm(primary_key)]
        pub id: i32,
        pub name: String,
        pub created_at: Json,
        #[sea_orm(unique)]
        pub session_token: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
        #[sea_orm(has_many = "super::transaction_records::Entity")]
        TransactionRecords,
}

impl Related<super::transaction_records::Entity> for Entity {
        fn to() -> RelationDef {
                Relation::TransactionRecords.def()
        }
}

impl ActiveModelBehavior for ActiveModel {}
